global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093" # Alertmanager 地址