global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9090']
  
  - job_name: 'message-service'
    static_configs:
      - targets: ['message-service:9090']
